#%RAML 1.0 NamedExample
1-example:

-
  External_id__c: 12341R
  Name: manideep
  phone__c: 86655452
  AccountNumber__c: 6445345RT
  Industry__c: Banking
  Active__c: Yes
  Email__c: karl@email.com
  Fax__c: 7484848
  BillingCity__c: KLA
  ShippingCity__c: MNA
  stamp_updated: '2021-04-30 16:31:57'
-
  External_id__c: 141R
  Name: manidep
  phone__c: 8665542
  AccountNumber__c: 64345RT
  Industry__c: Bankng
  Active__c: No
  Email__c: kuil@email.com
  Fax__c: 74848
  BillingCity__c: KUA
  ShippingCity__c: QNA
  stamp_updated: '2021-05-30 16:31:57'